### ISSUE TITLE
Table of contents for configuration docs

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit.dev#559] opened 2022-11-16 10:13 UTC
This is from our feedback session with the Anaconda team (packit/packit-service#1694):

The configuration documentation page https://packit.dev/docs/configuration/ has become quite long and it may be hard to find the needed info in there. Therefore, create a table of contents that would link logically grouped different parts/options of the configuration. In the right panel of the page, there are already links to the sections, but they may not be that visible and we could still create more sections to be able to find information faster.

**Comment by TomasTomecek** [comment] 2022-11-16 11:02
I'd go even a few steps further and completely revamp the page.

**Comment by TomasTomecek** [comment] 2022-12-07 10:01
Duplicate of https://github.com/packit/packit.dev/issues/467

**Closed by TomasTomecek** 2022-12-07 10:01 UTC
